### ISSUE TITLE
Expose solver choice to MATLAB

### ISSUE THREAD

**Issue by mikerouleau** [mikerouleau/CochleaSolver.jl#4]
RadauIIA5 is great and all, but choosing which solver and jacobian/mass matrix options should be exposed to users.

How to decide which solvers to allow?

**Comment by geosamaras** [comment]
'solver' variable in input .mat file, string (e.g. 'RadauIIA5')

**Comment by mikerouleau** [comment]
Is it important to expose solver options (eg autodiff=false) to MATLAB? Otherwise we can just set defaults.

**Comment by mikerouleau** [comment]
variable name changed to 'ODE_SOLVER'
